version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: civicbriefs
      POSTGRES_USER: civic
      POSTGRES_PASSWORD: civic
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
volumes:
  pgdata: {}

