name: Daily Agentic Run
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Prepare env
        run: |
          cp .env.example .env
      - name: Run once orchestrator
        run: |
          python -m app.agents.orchestrator --run-once

